def verify_nonce(result, target) -> bool: ...
def solve_challenge(prefix, target_hex) -> str: ...
def make_plain_lyrics(lyrics: str) -> str: ...
def do_publish(
    title: str, artist: str, album: str, duration: int, lyrics: str
) -> None: ...
